### ISSUE TITLE
master triggers a DMD ICE

### ISSUE THREAD

**Issue by BBasile** [rejectedsoftware/diet-ng#15] opened 2017-02-03 20:33 UTC
I've just pull from 6d1f556 to bfbbfe6 and build master under linux x86_64 and DMD 2.073.0. DMD crashes with 
> Internal error: tk.c 266

**Comment by s-ludwig** [comment] 2017-02-04 00:24
Since it only happens on DMD master (just added the latest versions to Travis: https://travis-ci.org/rejectedsoftware/diet-ng), this looks like it needs to be fixed in DMD directly. I could revert the commit here, but I can't realistically make any guarantees for development versions of the compiler anyway, and I'd rather avoid "supporting" compiler regressions unless one slipped through beta testing.

**Comment by BBasile** [comment] 2017-02-04 00:40
There might be a slight misunderstanding: I used lastest stable DMD it not a regression in DMD 2.074a.
Also the ICE only happens when building as a static library, not with the test config. Let's say that it was just a notification, I won't report to Dlang bugtracker.

**Comment by s-ludwig** [comment] 2017-02-04 02:01
Ah, okay, yes I misread that. I could reproduce it with `dub build -b release` and it looks like I'll indeed have to revert this.

**Comment by s-ludwig** [comment] 2017-02-05 00:26
Reported: https://issues.dlang.org/show_bug.cgi?id=17146

**Closed** 2017-02-05 00:27 UTC
